### ISSUE TITLE
Thumbs

### ISSUE THREAD

**Issue by pak11273** [Emiliano-Bucci/react-spring-carousel#11]
You use inline styles for the thumbs module which makes changing the flex styling for thumbs impossible.  Couldn't we put those styles into the class `use-spring-carousel-thumbs-wrapper` so they can be overridden?

**Comment by Emiliano-Bucci** [comment]
@pak11273 Hi! I've used inline styles because i didn't wanted to import any .css files. For the moment you can use the classNames that are attached to the carousel items and then use `!important`. I admit that i don't like this solution, and i've came up with a different solution; it will be implemented in the next small release :)

**Comment by pak11273** [comment]
!important 😢
